### ISSUE TITLE
Use secrets for secrets

### ISSUE THREAD

**Issue by anderius** [OctopusSamples/OctopusHelmChart#5]
Would it be an idea to use secrets and valueFrom.secretKeyRef (https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables) instead of just env variables that are visible directly in tools etc?

I am happy to create a PR if the plan sound good.

**Comment by mcasperson** [comment]
This is a good idea. Release 0.1.32 moves all the octopus secret values to a secret resource.
