### ISSUE TITLE
Add Ingress for exposing octopus

### ISSUE THREAD

**Issue by anderius** [OctopusSamples/OctopusHelmChart#6]
It would be helpful to include an Ingress to expose the application though nginx, traefik etc.

https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by mcasperson** [comment]
Ingress rules for a HA cluster is a little tricky. For ingress controllers like NGINX, there is an assumption that a service exposes HTTP and/or HTTPS traffic. Each Octopus node needs to expose both HTTPS traffic for the API, and HTTPS traffic for polling tentacles, and they must both be available on the same hostname.

We've enabled this via services, with is fairly straight forward. For ingress rules though you end up needing two ingress controllers, with one exposing the API traffic, and another exposing the polling tentacle. You then need a single public load balancer that is manually updated to direct port 10933 on the same hostname as the API traffic.

I don't believe there is a way to capture this configuration in a Helm chart with standard ingress resources. There will always be some external configuration that is load balancer specific to route all Octopus traffic through ingress rules.

**Comment by harrisonmeister** [comment]
Closing this issue as we have a replacement Helm chart [here](https://github.com/OctopusDeploy/helm-charts)
