### ISSUE TITLE
Deployment errors for "existing" installs

### ISSUE THREAD

**Issue by spyder007** [OctopusSamples/OctopusHelmChart#9]
When I first moved Octopus to Kubernetes, I had an existing installation, which means I had a database configured with authentication.  I do not, therefore, need the username/password values to be passed in via the environment variables.  Likewise, I am using the community edition, so the license key is not required.

The recent changes in moving these values to secrets have caused errors in deploying the helm charts when the values are not given.  

Also, I was running into "unbound" errors with the new server log volume mount.  I added the same logic to that volume template that exists in the other PVCs to correct the issue on my end.

I created a PR ( #8 ) to address both of these.

**Comment by harrisonmeister** [comment]
Addressed in #8
